import os


BCRYPT_LOG_ROUNDS = os.environ.get('BCRYPT_LOG_ROUNDS')
SECRET_KEY = os.environ.get('SECRET_KEY')
SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_TRACK_NOTIFICATIONS = os.environ.get('SQLALCHEMY_TRACK_NOTIFICATIONS')
DEBUG_TB_INTERCEPT_REDIRECTS  = os.environ.get('DEBUG_TB_INTERCEPT_REDIRECTS ')
